apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bgd
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: apps/bgd/overlays/bgd
    repoURL: https://github.com/muruganm0608/argocd-application.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
